name: Good First Issue Template
description: Create a Good First Issue for new contributors to the Hiero Website
title: "[Good First Issue]: "
labels: ["Good First Issue"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ---
        ## **Thanks for contributing!** 😊

        We truly appreciate your time and effort. If this is your first open-source contribution, welcome!
        This template is designed to help you create a Good First Issue (GFI): a small, well-scoped task that helps new contributors learn the codebase and workflow.
        ---

  - type: textarea
    id: intro
    attributes:
      label: 🆕🐥 Designed for New Contributors
      description: Who is this issue for?
      value: |
        This issue is reserved for people who have never contributed or have made minimal contributions to the [Hiero Website](https://github.com/hiero-ledger/hiero-website).
        We know that creating a pull request (PR) is a major barrier for new contributors.
        The goal of this issue and all other issues in [**find a good first issue**](https://github.com/issues?q=is%3Aopen+is%3Aissue+org%3Ahiero-ledger+archived%3Afalse+label%3A%22good+first+issue%22) is to help you make your first contribution to the Hiero Website.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > ### 📋 Good First Issue (GFI) Guidelines
        > A Good First Issue generally has a narrow scope and clear instructions, with examples or solutions provided.
        >        
        > Examples of acceptable GFI work include:
        >
        > - **Very small, explicitly defined changes to website code or content**
        >   - Fixing a broken link or image
        >   - Updating deprecated HTML tags or CSS classes
        >   - Correcting typos in text content
        > - **Documentation improvements** that are instruction-driven
        > - **Small, clearly specified edits** to existing examples or tests
        >
        > **What we do NOT consider Good First Issues:**
        >
        > - Writing new documentation or content without clear guidance
        > - Changes requiring architectural or design decisions
        > - Work spanning multiple subsystems
        >
        > 📖 *For more details, see:*  
        > [`.github/maintainers/guidelines_good_first_issues.md`](.github/maintainers/guidelines_good_first_issues.md)

  - type: textarea
    id: issue
    attributes:
      label: 👾 Description of the issue
      description: |
        DESCRIBE THE ISSUE IN A WAY THAT IS UNDERSTANDABLE TO NEW CONTRIBUTORS.
        ADD LINKS TO RELEVANT DOCUMENTATION OR CODE SECTIONS IF POSSIBLE.
      value: |
        Describe the issue here.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: |
        DESCRIBE THE STEPS NEEDED TO SOLVE THE ISSUE.
        BREAK DOWN THE STEPS AS MUCH AS POSSIBLE.
      value: |
        Edit here.
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: 👩‍💻 Implementation Steps
      description: |
        DESCRIBE THE TECHNICAL STEPS NEEDED TO SOLVE THE ISSUE.
      value: |
        Edit here.
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: Checklist of requirements for merging a PR
      value: |
        To be able to merge a pull request for this issue, we need:

        - [ ] **Issue is Solved:** The implementation fully addresses the issue requirements
        - [ ] **Netlify website previews as expected:** Netlify preview build is successful
        - [ ] **No Further Changes are Made:** Code review feedback has been addressed
    validations:
      required: true

  - type: textarea
    id: contribution_steps
    attributes:
      label: 📋 Step-by-Step Contribution Guide
      description: Provide a contribution workflow suitable for new contributors
      value: |
        If you have never contributed to an open source project at GitHub, the following steps will help:

        - [ ] **Read the README:** https://github.com/hiero-ledger/hiero-website/blob/main/README.md
        - [ ] **Fork, Branch and Work on the issue**
        - [ ] **DCO and GPG sign each commit:** https://github.com/hiero-ledger/hiero-website/blob/main/docs/signing.md
        - [ ] **Push and Create a Pull Request**
        - [ ] **You did it 🎉**
    validations:
      required: true

  - type: textarea
    id: information
    attributes:
      label: 🤔 Additional Information
      description: Provide extra resources or context for contributors
      value: |
        For more help:
        - Join our [Discord](https://github.com/hiero-ledger/hiero-website/blob/main/docs/discord.md)
        - [Hiero Website Community Calls](https://zoom-lfx.platform.linuxfoundation.org/meeting/94831465670?password=50e11cd2-6450-4a97-b9ae-7a7585c4409b)
        - [Hiero Community Calls](https://zoom-lfx.platform.linuxfoundation.org/meeting/97122675754?password=7eaa865a-2f17-4a7c-97b0-aff51933991c)
