name: Good First Issue Template
description: Create a Good First Issue for new contributors to the Hiero Website
title: "[Good First Issue]: "
labels: ["Good First Issue"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ---
        ## **Thanks for contributing!** 😊

        We truly appreciate your time and effort. If this is your first open-source contribution, welcome!
        This template is designed to help you create a Good First Issue (GFI): a small, well-scoped task that helps new contributors learn the codebase and workflow.
        ---

  - type: textarea
    id: intro
    attributes:
      label: 🆕🐥 Designed for New Contributors
      description: Who is this issue for?
      value: |
        This issue is reserved for people who have never contributed or have made minimal contributions to the [Hiero Website](https://github.com/hiero-ledger/hiero-website).
        We know that creating a pull request (PR) is a major barrier for new contributors.
        The goal of this issue and all other issues in [**find a good first issue**](https://github.com/issues?q=is%3Aopen%20is%3Aissue%20org%3Ahiero-ledger%20archived%3Afalse%20no%3Aassignee%20(label%3A%22good%20first%20issue%22%20OR%20label%3A%22skill%3A%20good%20first%20issue%22)%20(repo%3Ahiero-ledger%2Fhiero-sdk-cpp%20OR%20repo%3Ahiero-ledger%2Fhiero-sdk-swift%20OR%20repo%3Ahiero-ledger%2Fhiero-sdk-python%20OR%20repo%3Ahiero-ledger%2Fhiero-website)) is to help you make your first contribution to the Hiero Website.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > ### 📋 Good First Issue (GFI) Guidelines
        > A Good First Issue generally has a narrow scope and clear instructions, with examples or solution provided.
        >        
        > Examples of acceptable GFI work include:
        >
        > - **Very small, explicitly defined changes to website code or content**  
        >   *(rare and mechanical only — not behavior-changing)*, such as:
        >   - Fixing a broken link or image
        >   - Updating deprecated HTML tags or CSS classes
        >   - Correcting typos in text content
        > - **Refactors of existing examples or snippets** that are purely structural:
        >   - Splitting a long demo script into smaller functions
        >   - Combining multiple small snippets into one example  
        >   *(when explicitly instructed)*
        > - **Documentation improvements** that are instruction-driven:
        >   - Fixing known typos or grammar issues
        >   - Updating README sections when new wording is provided
        >   - Making explicitly requested changes to inline docs or comments
        > - **Functional improvements to examples**  
        >   *(only when the additional steps are explicitly described)*
        > - **Small, clearly specified edits to existing tests or lint rules**
        >
        > **What we do NOT consider Good First Issues:**
        >
        > - Writing new documentation, examples, or tests without clear guidance
        > - Any change that requires deciding *what* to do or *how* something should behave
        > - Changes to website architecture, frameworks, or public APIs
        > - Work spanning multiple subsystems or requiring deep design knowledge
        >
        > 📖 *For a more detailed explanation, refer to:  
        > [`.github/maintainers/guidelines_good_first_issues.md`](.github/maintainers/guidelines_good_first_issues.md).*


  - type: textarea
    id: issue
    attributes:
      label: 👾 Description of the issue
      description: |
        DESCRIBE THE ISSUE IN A WAY THAT IS UNDERSTANDABLE TO NEW CONTRIBUTORS.
        YOU MUST NOT ASSUME THAT SUCH CONTRIBUTORS HAVE ANY KNOWLEDGE ABOUT THE LANGUAGE, CODEBASE OR HIERO WEBSITE.
        IT IS HELPFUL TO ADD LINKS TO THE RELEVANT DOCUMENTATION AND/OR CODE SECTIONS.
      value: |
        Describe the issue here.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **💡 Example of a helpful Problem Description for GFI:**

        ### The Problem
        Several blog post images in the `content/posts` folder are missing "alt text" (alternative text).
        Alt text is important for accessibility—it helps screen readers describe images to visually
        impaired users. 

        Where to Find It
        The following blog posts need alt text added to their featured images:
        - `content/posts/tsc-voting-process.md` (line 3) - TSC voting banner image
        - `content/posts/python-office-hours.md` (line 3) - Python office hours image  
        - `content/posts/introducing-hiero-cli.md` (line 3) - Hiero CLI image

        Current Code Example
        Right now, the front matter looks like this:
        ```toml
        +++
        title = 'TSC Voting Process'
        featured_image = "/images/tsc-voting-process-post/TSCVotingProcessBanner_V1.jpg"
        date = 2025-04-29T10:12:50-07:00
        +++
        ```

        What Needs to Change
        While Hugo doesn't directly support alt text in front matter, we need to document
        which images need descriptive text for when we implement proper image handling. 

        Create a file `content/posts/IMAGE_ALT_TEXT.md` that lists: 
        - Image path
        - Suggested alt text
        - Which blog post uses it

        Why This Matters
        This documentation will help us improve accessibility when we implement
        proper image component handling across the site.

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: |
        DESCRIBE THE STEPS NEEDED TO SOLVE THE ISSUE.
        BREAK DOWN THE STEPS AS MUCH AS POSSIBLE AND MAKE SURE THEY ARE EASY TO FOLLOW.
        ADD LINKS TO RELEVANT DOCUMENTATION OR CODE SECTIONS IF POSSIBLE.
      value: |
        Edit here.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **💡 Example of a helpful Proposed Solution for GFI:**
        What Needs to Change
        Create a new markdown file that documents alt text for blog post featured images.

        1. Create the Documentation File
        - Create a new file: `content/posts/IMAGE_ALT_TEXT.md`
        - Copy the content from the Implementation Steps section below into that file
        - Save the file

        2. Verify Your Work
        - Make sure the file is in the correct location:  `content/posts/IMAGE_ALT_TEXT.md`
        - Check that all image paths match the actual images in the repository
        - Verify you've included all three blog posts mentioned

      

  - type: textarea
    id: implementation
    attributes:
      label: 👩‍💻 Implementation Steps
      description: |
        DESCRIBE THE TECHNICAL STEPS NEEDED TO SOLVE THE ISSUE.
        BREAK DOWN THE STEPS AS MUCH AS POSSIBLE AND MAKE SURE THEY ARE EASY TO FOLLOW.
      value: |
        Edit here.
    validations:
      required: true

  - type: markdown
    attributes:
      value:  |
        **💡 Example of helpful Implementation Steps for GFI:**
      
        Step-by-Step Implementation:
        File to Create
        **Location**: `content/posts/IMAGE_ALT_TEXT.md`

        **Content**:
        Featured Image Alt Text Documentation

        This file documents suggested alt text for blog post featured images
        for future accessibility improvements.

        Images Needing Alt Text

        TSC Voting Process Banner
        - **Image**: `/images/tsc-voting-process-post/TSCVotingProcessBanner_V1.jpg`
        - **Used in**: `content/posts/tsc-voting-process.md`
        - **Suggested alt text**: "Hiero Technical Steering Committee voting process banner with calendar and ballot icons"

        Python Office Hours
        - **Image**: `/images/python_office_hours.jpg`
        - **Used in**: `content/posts/python-office-hours.md`
        - **Suggested alt text**: "Python SDK office hours announcement with Hiero logo and Python logo"

        Hiero CLI Launch
        - **Image**: `/images/hiero-cli.png`
        - **Used in**: `content/posts/introducing-hiero-cli.md`
        - **Suggested alt text**: "Hiero CLI command line interface logo and branding"

        How to Write Good Alt Text
        - Be descriptive but concise
        - Describe what's in the image, not just repeat the title
        - Don't start with "Image of..." or "Picture of..."
        - Describe the relevant content or purpose of the image



  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: Checklist of requirements for merging a PR
      value: |
        To be able to merge a pull request for this issue, we need:

        - [ ] **Issue is Solved:** The implementation fully addresses the issue requirements
        - [ ] **Netlify website previews as expected:** Netlify preview build is successful and shows expected changes
        - [ ] **No Further Changes are Made:** Code review feedback has been addressed
    validations:
      required: true

  - type: textarea
    id: contribution_steps
    attributes:
      label: 📋 Step-by-Step Contribution Guide
      description: Provide a contribution workflow suitable for new contributors
      value: |
        If you have never contributed to an open source project at GitHub, the following step-by-step guide will introduce you to the workflow.
    
        - [ ] **Read the README:** Familiarize yourself with the project by reading the [README](https://github.com/hiero-ledger/hiero-website/blob/main/README.md)
        - [ ] **Fork, Branch and Work on the issue:** Create a fork, branch, and solve the problem. See [Contribution Guide](https://github.com/hiero-ledger/hiero-website/blob/main/docs/workflow.md)
        - [ ] **DCO and GPG key sign each commit:** each commit must be -s and -S signed. See [Signing Guide](https://github.com/hiero-ledger/hiero-website/blob/main/docs/signing.md)
        - [ ] **Push and Create a Pull Request:** Once your issue is resolved, push your changes and open a PR.
        - [ ] **You did it 🎉:** A maintainer will review and merge if approved.
    validations:
      required: true

  - type: textarea
    id: information
    attributes:
      label: 🤔 Additional Information
      description: Provide extra resources or context for contributors
      value: |
        For more help:
        - Join our [Discord](https://github.com/hiero-ledger/hiero-website/blob/main/docs/discord.md)
        - Attend our weekly community calls (see docs for schedule)
