name: Beginner Issue Template
description: Create a Beginner Issue for fairly new contributors to the Hiero Website
title: "[Beginner]: "
labels: ["beginner"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ---
        ## **Thanks for contributing!** 😊

        We truly appreciate your time and effort. If this is your first open-source contribution, welcome!
        This template is designed to help you create a Beginner-friendly issue: an easy, well-scoped task that helps fairly new contributors learn the codebase and build their skills.
        ---

  - type: textarea
    id: intro
    attributes:
      label: 🐥 Beginner Friendly
      description: Who is this issue for?
      value: |
        This issue is intended for contributors who have previously completed a Good First Issue in [Hiero Website](https://github.com/hiero-ledger/hiero-website) and are at a beginner level.
        We recognize that gaining confidence and building skills are equally important steps in the open-source contributor journey.
        The purpose of this issue—and others listed under [**Find a beginner issue**](https://github.com/hiero-ledger/hiero-website/issues?q=is%3Aissue%20state%3Aopen%20label%3Abeginner%20no%3Aassignee)—is to provide a supportive, low-pressure environment where you can learn, practice, and grow your contribution skills with confidence.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > ### 🐥 Beginner Issue Guidelines
        >
        > Beginner Issues are intended for contributors who are familiar with the project workflow and have **some programming or web development experience** and are wanting opportunities to build skills.
        > These issues may require **light investigation, interpretation of existing code, and some self-initiative**, but should remain **well-scoped with a clear intent**.
        >
        > **What we generally consider beginner issues:**
        >
        > - **Small, well-scoped updates to existing tests or lint rules**
        > - **Narrow changes or additions to website functionality** using common HTML/CSS/JS skills
        > - **Documentation improvements** in examples such as clarifying steps or adding missing details
        > - **Functional improvements to existing examples or snippets**
        >
        > **What we generally do NOT consider beginner issues:**
        > - Deep Hugo expertise or advanced frontend architecture work
        > - Tasks better suited for Good First Issues
        > - Changes to core website architecture or frameworks
        >
        > 📖 *For a more detailed explanation, refer to:*  
        > [`.github/guidelines_beginner_issues.md`](.github/guidelines_beginner_issues.md).

  - type: textarea
    id: issue
    attributes:
      label: 👾 Description of the issue
      description: |
        DESCRIBE THE ISSUE IN A WAY THAT IS UNDERSTANDABLE AND APPROACHABLE TO BEGINNER CONTRIBUTORS.
        ADD LINKS TO THE RELEVANT DOCUMENTATION AND/OR CODE SECTIONS.
      value: |
        Describe the issue here.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: |
        DESCRIBE THE STEPS NEEDED TO SOLVE THE ISSUE.
        BREAK DOWN THE STEPS AS MUCH AS POSSIBLE.
      value: |
        Edit here.
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: 👩‍💻 Implementation Steps
      description: |
        DESCRIBE THE TECHNICAL STEPS NEEDED TO SOLVE THE ISSUE.
      value: |
        Edit here.
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: Checklist of requirements for merging a PR
      value: |
        To be able to merge a pull request for this issue, we need:

        - [ ] **Issue is Solved:** The implementation fully addresses the issue requirements
        - [ ] **Netlify website previews as expected:** Netlify preview build is successful and shows expected changes
        - [ ] **No Further Changes are Made:** Code review feedback has been addressed
    validations:
      required: true

  - type: textarea
    id: contribution_steps
    attributes:
      label: 📋 Step-by-Step Contribution Guide
      description: Provide a contribution workflow suitable for new contributors
      value: |
        If you have never contributed to an open source project at GitHub, the following step-by-step guide will introduce you to the workflow.

        - [ ] **Read the README:** https://github.com/hiero-ledger/hiero-website/blob/main/README.md
        - [ ] **Fork, Branch and Work on the issue**
        - [ ] **DCO and GPG sign each commit:** https://github.com/hiero-ledger/hiero-website/blob/main/docs/signing.md
        - [ ] **Push and Create a Pull Request**
        - [ ] **You did it 🎉**
    validations:
      required: true

  - type: textarea
    id: information
    attributes:
      label: 🤔 Additional Information
      description: Provide extra resources or context for contributors
      value: |
        For more help:
        - Join our [Discord](https://github.com/hiero-ledger/hiero-website/blob/main/docs/discord.md)
        - [Hiero Website Community Calls](https://zoom-lfx.platform.linuxfoundation.org/meeting/94831465670?password=50e11cd2-6450-4a97-b9ae-7a7585c4409b)
        - [Hiero Community Calls](https://zoom-lfx.platform.linuxfoundation.org/meeting/97122675754?password=7eaa865a-2f17-4a7c-97b0-aff51933991c)
