name: Intermediate Website Issue Template
description: Create a well-documented issue for contributors with some familiarity with the Hiero Website codebase
title: "[Intermediate]: "
labels: ["intermediate"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ---
        ## **Thanks for contributing to the Hiero Website!** ðŸŒâœ¨

        We truly appreciate your time and effort.  
        This template is designed to help you create an **Intermediate issue** for the Hiero Website project.

        The goal is to create an issue for contributors who have:
        - basic familiarity with the Hiero Website codebase (HUGO, Tailwind, Markdown content, etc.)
        - experience following our contribution workflow
        - confidence navigating existing components, pages, and documentation
        ---

  - type: textarea
    id: intro
    attributes:
      label: ðŸ§© Intermediate Contributors
      description: Who is this issue for?
      value: |
        This issue is intended for contributors who are already very familiar with the
        [Hiero Website](https://github.com/hiero-ledger/hiero-website) codebase and its architectural patterns.
  
        You should feel comfortable with:
        - Netlify previews and tests
        - The Hiero website repository structure
        - understanding Hugo templating concepts without step-by-step guidance 
        - Editing and organizing Markdown at scale
        - Making pull requests with minimal guidance
        - navigating `layouts/`, `content/`, `partials/`, and `static/` 
        - following the standard PR workflow without additional onboarding

        If this is your very first contribution to the project, we recommend starting with a few
        **Good First Issues** before working on this one.
    validations:
      required: false

  - type: markdown
    attributes:
      value: | 
        > [!IMPORTANT] 
        > ### ðŸ§­ What we consider an *Intermediate Website Issue* 
        > 
        > This issue generally: 
        > 
        > - Requires **some knowledge of the Hugo codebase**, but not deep architectural knowledge 
        > - Is **narrowly scoped** and well-contained 
        > - Is **low to medium risk**, not touching highly sensitive or critical infrastructure 
        > - May involve **refactors, content restructuring, or small feature additions** 
        > - Provides **enough documentation or examples** to reason about a solution 
        > - Often has **similar patterns elsewhere in the codebase** 
        > 
        > **What this issue is NOT:** 
        > - A beginner-friendly onboarding task 
        > - A large architectural redesign of the site 
        > - A change requiring extensive cross-module refactors 
        > - A breaking change to site infrastructure or deployment

  - type: textarea
    id: problem
    attributes:
      label: ðŸž Problem Description
      description: |
        Describe the problem clearly and precisely.

        You may assume the reader:
        - understands the website structure
        - can navigate `layouts/`, `content/`, `partials/`, and `static/`
        - is comfortable reading existing implementations

        Still, explain:
        - what is wrong or missing
        - where it lives in the codebase
        - why it matters
      value: |
        Describe the problem here.
    validations:
      required: true

  - type: markdown
    attributes:
      value:  |
        **ðŸž Example of a helpful Problem Description:**

        Current Behavior
        The search functionality on the Hiero website currently uses client-side JavaScript to search through page content. 
        This works well for small sites, but our website has grown to 200+ pages, causing: 
        - Search indexing to take 3-5 seconds on initial page load
        - High memory usage on mobile devices (often causing crashes on older phones)
        - Poor search relevance for technical terms (no stemming or fuzzy matching)

        Why This Matters
        User analytics show that 40% of visitors use the search feature, and bounce rate increases by 25% 
        when search takes longer than 2 seconds to initialize.

        Components Involved
        - `/layouts/partials/search.html` - Main search UI component
        - `/static/js/search.js` - Client-side search logic
        - `/layouts/_default/baseof.html` - Where search scripts are loaded
        - Content files across `/content/` directory (all indexed)

        Historical Context
        The current implementation was added in PR #42 when the site had only 30 pages.

  - type: textarea
    id: solution
    attributes:
      label: ðŸ’¡ Expected Solution
      description: |
        Describe the intended outcome.

        This does NOT need to be a full implementation plan,
        but should explain:
        - what should change
        - what should NOT change
        - any constraints or boundaries
      value: |
        Describe the expected solution here.
    validations:
      required: true
    
  - type:  markdown
    attributes:
      value:  |
        **ðŸ’¡ Example of a helpful Proposed Solution:**

        Approach:
        Migrate from client-side search to a pre-built search index using Hugo's built-in search capabilities 
        with Fuse.js or Pagefind. 

        Key Changes:
        1. **Build-time indexing**: Generate a JSON search index during Hugo build
        2. **Lazy loading**: Only load search scripts when the user opens the search UI
        3. **Improved relevance**: Use Fuse.js fuzzy search with weighted fields (title > headings > body)

        Constraints:
        - **Must maintain current search UI/UX** - users are familiar with the existing interface
        - **Backwards compatible URLs** - search query parameters should continue to work
        - **Accessibility** - maintain ARIA labels and keyboard navigation
        - **Performance target**: Search index should load in < 500ms on 3G connection

        Alternatives Considered:
        - **Algolia/External Service**: Rejected due to cost and privacy concerns
        - **Full Server-Side Search**: Rejected because we're a static site (no backend)
        - **Keep Current Approach**: Would require significant optimization with diminishing returns


  - type: textarea
    id: implementation
    attributes:
      label: ðŸ§  Implementation Notes
      description: |
        Provide technical guidance to help implementation.

        Examples:
        - files or modules likely involved
        - patterns already used elsewhere
        - things to be careful about
        - known edge cases
      value: |
        Add implementation notes here.
    validations:
      required: false

  - type: markdown
    attributes:
      value:  |
        **ðŸ§  Example of helpful Implementation Notes:**

        Modules and Components
        
        Files to Modify
        - `/layouts/partials/search.html` - Update to load search index
        - `/static/js/search.js` - Replace with Fuse.js implementation
        - `/layouts/index.json` - Create new search index template
        - `/config.toml` - Add output format for JSON index

        Files to Add
        - `/static/js/fuse.min.js` - Fuse.js library (version 6.6.2)
        - `/layouts/_default/search-index.json` - Template for search entries

        Suggested Refactoring Strategy
        
        1. **Phase 1**: Create JSON index without breaking existing search
           - Add new `index.json` output format
           - Generate search index at build time
           - Test index generation locally
        
        2. **Phase 2**:  Implement lazy loading
           - Wrap search script loading in intersection observer
           - Add loading state to search UI
           - Test on slow connections
        
        3. **Phase 3**: Replace search logic
           - Swap out old search.js with Fuse.js implementation
           - Maintain existing search API/interface
           - Run A/B comparison of search results quality

        Migration Concerns:
        - Existing bookmarks with search queries must continue to work
        - Search index should be cached by CDN (set appropriate headers)
        - Consider index size - may need to exclude certain content types

        Testing Strategy:
        - Unit tests for search index generation
        - E2E tests for search UI interaction (Playwright)
        - Performance tests:  measure index load time and search speed
        - Accessibility audit with screen reader
        - Test on mobile devices (iOS Safari, Android Chrome)

        Performance Considerations:
        - Search index size should be < 500KB gzipped
        - Consider splitting index by section if it grows too large
        - Use CDN caching headers (1 week cache, revalidate on deploy)

        Security Considerations:
        - Ensure search index doesn't include draft/private content
        - Validate search queries to prevent XSS (though Fuse.js handles this)

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: âœ… Acceptance Criteria
      description: Define what "done" means for this issue
      value: |
        To merge this issue, the pull request must:

        - [ ] Fully address the problem described above
        - [ ] Follow existing project conventions and patterns
        - [ ] Include tests or example updates where appropriate
        - [ ] Pass all CI checks
        - [ ] Include a valid changelog entry
        - [ ] Use DCO and GPG-signed commits
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: ðŸ“š Additional Context or Resources
      description: |
        Add any links, references, or extra notes that may help.
      value: |
        - [Website Developer Docs](https://github.com/hiero-ledger/hiero-website/tree/main/docs)
    validations:
      required: false
