# SPDX-License-Identifier: Apache-2.0

name: "PR Formatting"
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

defaults:
  run:
    shell: bash

permissions:
  contents: read
  statuses: write

concurrency:
  group: pr-formatting-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  title-check:
    name: Title Check
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Check PR Title
        uses: step-security/conventional-pr-title-action@bb2263ec311ca158e9ffa6bd9b997fb425402034 # v3.2.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
